version: '3.9'

services:
  web:
    image: alexsearle/my_repo
    build: /ngnix
    ports:
      - 80:80
      - 433:433
    env_file:
      - .env
  website:
    image: alexsearle/my_repo
    build: /app
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - .env    
